WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002651B4E77D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e90da0f1c4f410b8564faa516cb1679e
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002651B0DDD10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e90da0f1c4f410b8564faa516cb1679e
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002651B4F8490>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e90da0f1c4f410b8564faa516cb1679e