WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027A020616D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/231588bae79ce4edad8941918c1c0e83
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027A02061D10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/231588bae79ce4edad8941918c1c0e83
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027A02062450>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/231588bae79ce4edad8941918c1c0e83