WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002265EDF1890>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/3fe0db04b729a437d5a6c870411f2f1e
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002265ED9C650>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/3fe0db04b729a437d5a6c870411f2f1e
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002265EDF2550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/3fe0db04b729a437d5a6c870411f2f1e