WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027DED4E79D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c12d1f312b03fdcaa3293e9c14143f34
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027DED49C490>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c12d1f312b03fdcaa3293e9c14143f34
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027DED4F8690>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c12d1f312b03fdcaa3293e9c14143f34