WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027D58C17550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/34478d98fb20ef397c46810af7bd972c
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027D58BC0B10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/34478d98fb20ef397c46810af7bd972c
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027D58C281D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/34478d98fb20ef397c46810af7bd972c