WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CAAC96B3D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/a5160cd2e8781506fff7a1d9a88bfb0c
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CAAC54A750>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/a5160cd2e8781506fff7a1d9a88bfb0c
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CAAC978190>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/a5160cd2e8781506fff7a1d9a88bfb0c