WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028A1BF92390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e4594ffdf539626057f5b22a82cd9d89
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028A1BF6D9D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e4594ffdf539626057f5b22a82cd9d89
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028A1BF93090>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e4594ffdf539626057f5b22a82cd9d89