WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CF23FD7990>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/2890d4f7114e5067855eba4e337d8d56
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CF23F62750>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/2890d4f7114e5067855eba4e337d8d56
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CF23FE8550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/2890d4f7114e5067855eba4e337d8d56