WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BDF7192A10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/15e9f42e1a92b620fd6d016780c75be1
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BDF715C650>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/15e9f42e1a92b620fd6d016780c75be1
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BDF7193690>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/15e9f42e1a92b620fd6d016780c75be1