WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EFBE5177D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/135c677aa6d5510a014b27631be5e24a
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EFBE454710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/135c677aa6d5510a014b27631be5e24a
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EFBE520390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/135c677aa6d5510a014b27631be5e24a