WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000175189C6B50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/43c446e44433dd29df6e62f3a7d098d5
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000175176C0890>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/43c446e44433dd29df6e62f3a7d098d5
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000175189C7850>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/43c446e44433dd29df6e62f3a7d098d5