WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016FBBC1AB10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d16b73262bcf25292de9a6516b8100e0
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016FBBBDC490>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d16b73262bcf25292de9a6516b8100e0
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016FBBC1B890>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d16b73262bcf25292de9a6516b8100e0