WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019EF17C7850>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/80f58170b78c7a1718c584e3744532a8
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019EF1770F50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/80f58170b78c7a1718c584e3744532a8
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019EF17D8550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/80f58170b78c7a1718c584e3744532a8